# Generated by Django 4.0.4 on 2023-04-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='faculty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='images/profile_pics'),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
