# Generated by Django 4.0.4 on 2023-04-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_coordinator_faculty_coordinator_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='profile_pic',
            field=models.ImageField(default='images/default.png', upload_to='images/profile_pics'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='images/photos'),
        ),
    ]
