# Generated by Django 4.0.4 on 2023-04-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_coordinator_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='linked_in',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
