# Generated by Django 4.0.4 on 2023-04-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_coordinator_linked_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='w_chapter',
            field=models.BooleanField(default=False),
        ),
    ]
