# Generated by Django 4.0.4 on 2023-04-10 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_coordinator_w_chapter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coordinator',
            new_name='Member',
        ),
    ]
