# Generated by Django 4.2 on 2023-04-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_member_github_student_event_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='year',
            field=models.CharField(choices=[('1st', 'First year'), ('2nd', 'Second year'), ('3rd', 'Third year')], default='1st', max_length=20),
        ),
    ]
