# Generated by Django 4.2 on 2023-04-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_member_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('1st', 'First year'), ('2nd', 'Second year'), ('3rd', 'Third year')], default='1st', max_length=20),
        ),
    ]
