# Generated by Django 4.2 on 2023-04-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_student_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='coordinator',
            field=models.ManyToManyField(blank=True, related_name='coordinated', to='base.member'),
        ),
    ]
