# Generated by Django 4.2 on 2023-04-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_event_coordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_participants',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='participated', to='base.student'),
        ),
    ]
