# Generated by Django 4.2 on 2023-04-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_event_event_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_participants',
            field=models.ManyToManyField(blank=True, default='', related_name='participated', to='base.student'),
        ),
    ]
