# Generated by Django 4.2 on 2023-04-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_event_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
