# Generated by Django 4.2 on 2023-04-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_student_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='desc',
            field=models.TextField(blank=True, default='Hello my name is <django.db.models.fields.CharField>'),
        ),
    ]
