# Generated by Django 4.2 on 2023-04-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_student_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='desc',
            field=models.TextField(blank=True, default='Hello my name is <django.db.models.fields.CharField>'),
        ),
    ]
