# Generated by Django 4.2 on 2023-04-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_remove_event_description_event_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='desc',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='desc',
            field=models.TextField(blank=True, default='Hello my name is <django.db.models.fields.CharField>'),
        ),
    ]
