# Generated by Django 4.2 on 2023-05-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_member_desc_alter_student_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='admission',
            field=models.CharField(default='', max_length=50),
        ),
    ]
