# Generated by Django 4.2 on 2023-05-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_member_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission',
            field=models.CharField(default='', max_length=50),
        ),
    ]
