# Generated by Django 4.2 on 2023-05-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='short_desc',
            field=models.TextField(blank=True, default="Hello, I love being in ACM's core team"),
        ),
    ]
