# Generated by Django 4.2 on 2023-05-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_member_short_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='team_event',
            field=models.IntegerField(default=1),
        ),
    ]
