# Generated by Django 4.2 on 2023-05-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_event_team_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='team_event',
            new_name='team_members',
        ),
    ]
