# Generated by Django 4.2 on 2023-05-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_rename_team_event_event_team_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='team',
        ),
    ]
