# Generated by Django 4.2 on 2023-05-03 15:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='base.event')),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='base.student')),
                ('member1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member1', to='base.student')),
                ('member2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member2', to='base.student')),
                ('member3', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member3', to='base.student')),
                ('member4', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member4', to='base.student')),
            ],
        ),
    ]
