# Generated by Django 4.2 on 2023-05-03 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
