# Generated by Django 4.2 on 2023-05-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_teammembership_is_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='participation',
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='team',
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participated', to='base.student'),
        ),
        migrations.DeleteModel(
            name='Participation',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamMembership',
        ),
    ]
