# Generated by Django 4.2 on 2023-05-04 08:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_remove_team_members_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True)),
                ('event', models.ManyToManyField(related_name='teams', to='base.event')),
                ('leaders', models.ManyToManyField(related_name='team_leader', to='base.student')),
                ('members', models.ManyToManyField(blank=True, related_name='myteams', to='base.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='member', to='base.team'),
        ),
    ]
