# Generated by Django 4.2 on 2023-05-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='mobile_no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile_no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='events', to='base.tag'),
        ),
    ]
