# Generated by Django 4.2 on 2023-05-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_tag_member_mobile_no_student_mobile_no_event_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='admission',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
