# Generated by Django 4.2 on 2023-05-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_alter_member_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='first',
            field=models.ManyToManyField(blank=True, related_name='first', to='base.student'),
        ),
        migrations.AddField(
            model_name='event',
            name='second',
            field=models.ManyToManyField(blank=True, related_name='second', to='base.student'),
        ),
        migrations.AddField(
            model_name='event',
            name='third',
            field=models.ManyToManyField(blank=True, related_name='third', to='base.student'),
        ),
    ]
