# Generated by Django 4.2 on 2023-06-07 09:40

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_event_first_event_second_event_third'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='unique_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='url_timeout',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='unique_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='url_timeout',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to=base.models.nameEventImage),
        ),
        migrations.AlterField(
            model_name='member',
            name='desc',
            field=models.TextField(blank=True, default="Hello, I love being in ACM's core team", max_length=500),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(default='images/profile_pics/default.png', upload_to=base.models.nameAndOverwriteMemberImage),
        ),
        migrations.AlterField(
            model_name='member',
            name='short_desc',
            field=models.CharField(blank=True, default="Hello, I love being in ACM's core team", max_length=120),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=base.models.nameEventPhotos),
        ),
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='desc',
            field=models.TextField(blank=True, default='Hello, I promise to be awesome!!', max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(default='images/profile_pics/default.png', upload_to=base.models.nameAndOverwriteStudentImage),
        )
    ]
