# Generated by Django 4.2 on 2023-06-08 11:08

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_news_member_unique_url_member_url_timeout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=80)),
                ('image', models.ImageField(blank=True, upload_to=base.models.nameNewsImage)),
                ('desc', models.TextField(max_length=300)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Byte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('byte', models.CharField(max_length=120)),
                ('created', models.DateTimeField(editable=False)),
                ('edited', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mybytes', to='base.member')),
            ],
        ),
    ]
