# Generated by Django 4.2 on 2023-06-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_news_byte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='year',
            field=models.CharField(choices=[('1st', 'First year'), ('2nd', 'Second year'), ('3rd', 'Third year'), ('4th', 'Fourth year'), ('other', 'Other')], default='1st', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('1st', 'First year'), ('2nd', 'Second year'), ('3rd', 'Third year'), ('4th', 'Fourth year'), ('other', 'Other')], default='1st', max_length=20),
        ),
    ]
