# Generated by Django 4.2 on 2023-06-08 13:30

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_alter_member_year_alter_student_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mobile_no',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profile_pics/default.png', upload_to=base.models.nameAndOverwriteMemberImage),
        ),
        migrations.AlterField(
            model_name='member',
            name='url_timeout',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_no',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profile_pics/default.png', upload_to=base.models.nameAndOverwriteStudentImage),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('1st', 'First year'), ('2nd', 'Second year'), ('3rd', 'Third year'), ('4th', 'Fourth year'), ('Alumni', 'Alumni')], default='1st', max_length=20),
        ),
    ]
