# Generated by Django 4.2 on 2023-06-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_alter_member_mobile_no_alter_member_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='year',
            field=models.CharField(choices=[('1st', 'First year'), ('2nd', 'Second year'), ('3rd', 'Third year'), ('4th', 'Fourth year'), ('faculty', 'Faculty'), ('alumni', 'Alumni')], default='1st', max_length=20),
        ),
    ]
