# Generated by Django 4.2 on 2023-09-02 12:32

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_alter_member_year_alter_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_bg_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_text_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
