# Generated by Django 4.2 on 2023-10-11 14:50

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_tag_tag_bg_color_tag_tag_text_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_bg_color',
            new_name='Theme',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag_text_color',
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profile_pics/default.jpg', upload_to=base.models.nameAndOverwriteMemberImage),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profile_pics/default.jpg', upload_to=base.models.nameAndOverwriteStudentImage),
        ),
    ]
