# Generated by Django 4.2 on 2023-10-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_rename_tag_bg_color_tag_theme_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='Theme',
            new_name='theme',
        ),
    ]
