# Generated by Django 4.2 on 2023-10-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_rename_theme_tag_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(blank=True, default='Member', max_length=100, null=True),
        ),
    ]
