# Generated by Django 4.2 on 2023-11-04 18:37

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_alter_member_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='byte',
            name='poster',
            field=models.ImageField(blank=True, upload_to=base.models.nameBytePoster),
        ),
    ]
