# Generated by Django 4.2 on 2023-11-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_byte_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='byte',
            name='byte',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='byte',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='byte',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
