# Generated by Django 4.2 on 2023-11-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_alter_byte_byte_alter_byte_created_alter_byte_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='byte',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
