# Generated by Django 4.2 on 2023-11-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_byte_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='byte',
            name='likes',
        ),
        migrations.AddField(
            model_name='byte',
            name='likes',
            field=models.ManyToManyField(blank=True, default='', related_name='liked', to='base.member'),
        ),
    ]
