# Generated by Django 4.2 on 2023-11-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_remove_byte_likes_byte_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='byte',
            name='likes2',
            field=models.ManyToManyField(blank=True, default='', related_name='liked', to='base.student'),
        ),
    ]
