# Generated by Django 4.2 on 2023-11-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_byte_likes2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='byte',
            old_name='likes2',
            new_name='studentLikes',
        ),
        migrations.AddField(
            model_name='byte',
            name='memberLikes',
            field=models.ManyToManyField(blank=True, default='', related_name='liked', to='base.member'),
        ),
        migrations.RemoveField(
            model_name='byte',
            name='likes',
        ),
        migrations.AddField(
            model_name='byte',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
