# Generated by Django 4.2 on 2023-11-04 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0074_remove_byte_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='byte',
            name='owner',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mybytes', to=settings.AUTH_USER_MODEL),
        ),
    ]
