# Generated by Django 4.2 on 2024-01-25 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_byte_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='base.event')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option', models.TextField()),
                ('belongsTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='base.eventmeta')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='base.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='base.student')),
            ],
        ),
        migrations.AddField(
            model_name='eventmeta',
            name='responses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mete', to='base.questionresponse'),
        ),
    ]
