# Generated by Django 4.2 on 2024-01-25 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0076_eventmeta_question_questionresponse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='belongsTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='base.event'),
        ),
        migrations.DeleteModel(
            name='EventMeta',
        ),
    ]
