# Generated by Django 4.2 on 2024-02-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0078_alter_byte_byte_alter_byte_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='byte',
            name='byte',
            field=models.TextField(),
        ),
    ]
